=== iesgrancapitan-llmm/mi-primera-pagina-web-valfrio/UD5/A1/alumnosDTD.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellidos, ciclo, (nota_media | nota_final))>
<!ATTLIST alumno
          expediente CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT nota_final (#PCDATA)>
<!ELEMENT nota_media (#PCDATA)>

=== iesgrancapitan-llmm/mi-primera-pagina-web-valfrio/UD5/A1/alumnos externo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML y crear esquema DTD: esto en xml copy editor-->
<!--Para introducir uno externo en XML copy editor: se guarda y en el xml le das xml - asociar system dtt-->


<!DOCTYPE alumnos SYSTEM "./alumnosDTD.dtd">

<alumnos>
    <alumno expediente="A001">
        <nombre>Salvador</nombre>
        <apellidos>Martinez</apellidos>
        <ciclo>DAW</ciclo>
        <nota_final>10</nota_final>
    </alumno>
    <alumno expediente="A002">
        <nombre>Kike</nombre>
        <apellidos>Mari√±o</apellidos>
        <ciclo>DAW</ciclo>
        <nota_media>10</nota_media>
    </alumno>
</alumnos>
