<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio [
    <!ELEMENT colegio (alumnos, profes)>
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre, apellido, matricula, activo?)>
    <!ATTLIST alumno expediente CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT activo EMPTY>
    <!ELEMENT profes (profe+)>
    <!ELEMENT profe (nombre, curso, foto)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
]>
<colegio>
    <alumnos>
        <alumno expediente="AA01">
            <nombre>Salva</nombre>
            <apellido>Martínez</apellido>
            <matricula>DAW</matricula>
            <activo/>
        </alumno>
        <alumno expediente="AA02">
            <nombre>Enrique</nombre>
            <apellido>Mariño</apellido>
            <matricula>DAW</matricula>
        </alumno>
    </alumnos>
    <profes>
        <profe>
            <nombre>Jorge</nombre>
            <curso>DAW</curso>
            <foto>Jorge.png</foto>
        </profe>
    </profes>
</colegio>