<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos[
<!ELEMENT partidos (equipo-local, equipo-visitante)>
<!ELEMENT equipo-local (nombre, goles)>
<!ELEMENT equipo-visitante (nombre, goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
]>

<partidos>
    <equipo-local>
        <nombre>Nottingham Presa</nombre>
        <goles>0</goles>
    </equipo-local>
    <equipo-visitante>
        <nombre>Inter de Mitente</nombre>
        <goles>1</goles>
    </equipo-visitante>
</partidos>